<a href="https://colab.research.google.com/github/RanjaneSiddhesh/genai/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
# Tensor creation
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.ones((2, 2))
c = tf.random.uniform((2, 2), 0, 10)

# Basic operations
print("a + b:\n", a + b)
print("a * c:\n", a * c)
print("a @ b:\n", a @ b)

# Manipulation
print("Reshape a:\n", tf.reshape(a, (4, 1)))
print("Slice a[0]:", a[0])

# Computation graph with tf.function
@tf.function
def compute(x, y):
    return tf.sqrt(x**2 + y**2)

print("Graph result:\n", compute(a, b))

# Eager execution example
for i in range(2):
    x = tf.random.uniform((2, 2))
    print(f"Run {i+1}, mean:", tf.reduce_mean(x).numpy())


a + b:
 tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)
a * c:
 tf.Tensor(
[[ 1.3967776   0.45256853]
 [24.011177    3.4618711 ]], shape=(2, 2), dtype=float32)
a @ b:
 tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32)
Reshape a:
 tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]], shape=(4, 1), dtype=float32)
Slice a[0]: tf.Tensor([1. 2.], shape=(2,), dtype=float32)
Graph result:
 tf.Tensor(
[[1.4142135 2.236068 ]
 [3.1622777 4.1231055]], shape=(2, 2), dtype=float32)
Run 1, mean: 0.47597882
Run 2, mean: 0.6210644
